Resources:
  LadokParseResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.LadokParseResults}
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
