service: zk-authentication

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

stage: prod
region: eu-central-1

functions:
  createUserPool:
    handler: src/lambda/userPool.create
    events:
      - http:
          path: userPool/create
          method: put
