service: operis-billable-time

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  Invoices: 'Invoices-${self:custom.stage}'
  Recipients: 'Recipients-${self:custom.stage}'
  CompanyCustomers: 'CompanyCustomers-${self:custom.stage}'
  serverless-offline:
    port: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: CompanyCustomers
            sources: [./offline/seeds/company-customer.json]

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["InvoicesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["RecipientsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["CompanyCustomersDynamoDBTable", "Arn" ] }
  environment:
    InvoicesTable: ${self:custom.Invoices}
    RecipientsTable: ${self:custom.Recipients}
    CompanyCustomersTable: ${self:custom.CompanyCustomers}

functions:
  dibsConfirm:
    handler: src/lambda/dibs.confirm
    events:
      - http:
          method: post
          path: dibs/confirm
          role: callPaymentLambdas
  createPlanInvoice:
    handler: src/lambda/plan.createInvoice
    events:
      - http:
         method: post
         path: /charge/plan
         role: paymentDatabaseManager
         cors: true
         authorizer: aws_iam
  createPlan:
    handler: src/lambda/plan.create
    events:
      - http:
         method: post
         path: /plan/create
         role: paymentDatabaseManager
         cors: true
         authorizer: aws_iam
  setInvoiceStatus:
    handler: src/lambda/invoice.setStatus
    events:
      - http:
         method: post
         path: /invoice/status
         role: paymentDatabaseManager
         cors: true
         authorizer: aws_iam
  createInvoice:
    handler: src/handler.writeInvoice
    events:
      - http:
          path: /invoice
          method: post
          cors: true
          authorizer: aws_iam
  sendInvoice:
    handler: src/handler.sendInvoice
    events:
      - http:
          path: /invoice/mail
          method: post
          cors: true
          authorizer: aws_iam
  getInvoices:
    handler: src/handler.getInvoices
    events:
      - http:
          path: /invoice/{companyCustomerId}
          method: get
          cors: true
          authorizer: aws_iam
  createRecipient:
    handler: src/handler.createRecipient
    events:
      - http:
          path: /recipient
          method: post
          cors: true
          authorizer: aws_iam
  getRecipients:
    handler: src/handler.getRecipients
    events:
      - http:
          path: /recipient/{companyCustomerId}
          method: get
          cors: true
          authorizer: aws_iam


package:
  exclude:
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**

resources:
  Resources:
    callPaymentLambdas:
      Type: AWS::IAM::Role
      Properties:
        RoleName: callPaymentLambdas
        Path: "/"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
            - PolicyName: CallPaymentDatabaseManagers
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                  - Effect: Allow
                    Action:
                      - lambda:InvokeFunction
                    Resource: arn:aws:lambda:eu-central-1:460056602695:function:payment-prod-membrumSavePayment
    paymentDatabaseManager:
      Type: AWS::IAM::Role
      Properties:
        RoleName: paymentDatabaseManager
        Path: "/"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
            - PolicyName: ManagePaymentTable
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                  - Effect: Allow
                    Action:
                      - dynamodb:*
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPaymentStatuses
                  - Effect: Allow
                    Action:
                      - dynamodb:scan
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPlans
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPaymentStatuses/statusId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPaymentStatuses/index/paymentId
                  - Effect: Allow
                    Action:
                      - dynamodb:*
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments/orderId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments/index/userId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumUsers
    CompanyCustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CompanyCustomers
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    InvoicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Invoices
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    InvoiceStatusesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InvoiceStatuses
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    RecipientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Recipients
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
