# NOTE: update this with your service name
service: operis-billable-time

package:

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# Enable auto-packing of external modules
custom:
  serverless-offline:
    babelOptions:
      presets: ["env"]
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["InvoiceDynamoDBTable", "Arn" ] }
  environment:
    CompanyCustomersTable: ${self:custom.CompanyCustomers}

functions:
  createInvoice:
    handler: src/handler.createCompanyCustomer
    events:
      - http:
          path: /invoicepdf/{invoiceId}
          method: get
