service: payment

provider:
  name: aws
  runtime: java8
  stage: prod
  region: eu-central-1

package:
  artifact: target/PaymentLambda.jar

functions:
  confirmPayment:
    handler: com.zetta.payment.lambda.PaymentLambda::dibsConfirmation
    events:
      - http:
          method: post
          path: confirm
  generateDibsUrl:
    handler: com.zetta.payment.lambda.PaymentLambda::getDIBSUrl
    events:
      - http:
         method: get
         path: url
         role: paymentDatabaseManager
         cors: true
  getOrder:
    handler: com.zetta.payment.lambda.PaymentLambda::lambdaGetOrder
    events:
      - http:
         method: get
         path: getOrder
         role: paymentDatabaseManager
         cors: true

resources:
  Resources:
    paymentDatabaseManager:
      Type: AWS::IAM::Role
      Properties:
        RoleName: paymentDatabaseManager
        Path: "/"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
            - PolicyName: ManagePaymentTable
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayment-Test
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumUser-Test