service: payment

provider:
  name: aws
  runtime: java8
  stage: prod
  region: eu-central-1

package:
  artifact: target/PaymentLambda.jar

functions:
  membrumDIBSConfirm:
    handler: com.zetta.payment.lambda.membrum.MembrumDIBSConfirm::membrumDIBSConfirm
    events:
      - http:
          method: post
          path: confirmPayment
          role: callPaymentLambdas
  membrumNextOrder:
    handler: com.zetta.payment.lambda.membrum.MembrumNextOrder::membrumNextOrder
    events:
      - http:
         method: get
         path: getNextOrder
         role: paymentDatabaseManager
         cors: true
  membrumSavePayment:
    handler: com.zetta.payment.lambda.membrum.MembrumSavePayment::membrumSavePayment
    events:
      - http:
         method: put
         path: updateOrder
         role: paymentDatabaseManager
         cors: true

resources:
  Resources:
    callPaymentLambdas:
      Type: AWS::IAM::Role
      Properties:
        RoleName: callPaymentLambdas
        Path: "/"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
            - PolicyName: CallPaymentDatabaseManagers
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                  - Effect: Allow
                    Action:
                      - lambda:InvokeFunction
                    Resource: arn:aws:lambda:eu-central-1:460056602695:function:payment-prod-membrumSavePayment
    paymentDatabaseManager:
      Type: AWS::IAM::Role
      Properties:
        RoleName: paymentDatabaseManager
        Path: "/"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
            - PolicyName: ManagePaymentTable
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                  - Effect: Allow
                    Action:
                      - dynamodb:*
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumOrders
                  - Effect: Allow
                    Action:
                      - dynamodb:scan
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPlans
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumOrders/orderId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumOrders/index/userId
                  - Effect: Allow
                    Action:
                      - dynamodb:*
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments/orderId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumPayments/index/userId
                  - Effect: Allow
                    Action:
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:Query
                    Resource: arn:aws:dynamodb:eu-central-1:460056602695:table/MembrumUsers
