service: payment

provider:
  name: aws
  runtime: java8
  stage: prod
  region: eu-central-1

package:
  artifact: target/PaymentLambda.jar

functions:
  confirmPayment:
    handler: com.zetta.payment.lambda.PaymentLambda::dibsConfirmation
    events:
      - http:
          path: confirm
          method: post