service: ladokParser

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:eu-central-1:460056602695:table/LadokParseResult"
    - Effect: Allow
      Action:
        - s3:getObject
      Resource:
        - arn:aws:s3:::ladok-files/*

functions:
  assignLadokPeople:
    handler: src/lambda/assign.getParseResults
    events:
      - http:
          path: assignLadok
          method: get
          cors: true
          authorizer: aws_iam

  parseUploadedFile:
    handler: src/lambda/parse.parseUploadedFile
    events:
      - http:
          path: parseLadok
          method: post
          cors: true
          authorizer: aws_iam
