service: ladokParser

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

  stage: ${opt:stage, self:provider.stage}
  LadokParseResults: 'LadokParseResults-${self:custom.stage}'
  Recipients: 'Recipients-${self:custom.stage}'
  S3UploadFolder: 'ladok-uploads-${self:custom.stage}'

  serverless-offline:
    port: 8080
    babelOptions:
      presets: ["env", "flow"]
  s3:
    port: 8040
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false
    seed:
      domain:
        sources:
          - table: ${self:custom.LadokParseResults}
            sources: [./offline/seeds/ladokParseResults.json]
          - table: ${self:custom.Recipients}
            sources: [./offline/seeds/recipients.json]

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["LadokParseResultsTable", "Arn" ] }
        - { "Fn::GetAtt": ["RecipientsTable", "Arn"] }

    - Effect: Allow
      Action:
        - s3:getObject
      Resource:
        - { "Fn::GetAtt": ["S3UploadBucket", "Arn"] }

  environment:
    S3UploadFolder: ${self:custom.S3UploadFolder}
    LadokParseResults: ${self:custom.LadokParseResults}
    Recipients: ${self:custom.Recipients}

functions:
  #This returns the result of all assignment results
  getNewAssignments:
    handler: src/lambda/getAssignments.getNewAssignments
    events:
      - http:
          path: assignments/get
          method: get
          cors: true

  #This is the commit of for all the parsed files
  saveNewAssignments:
    handler: src/lambda/saveAssignments.saveNewAssignments
    events:
      - http:
          path: assignments/save
          method: put
          cors: true

  #Should be invoked when a file is uploaded
  parseUploadedFile:
    handler: src/lambda/parse.parseUploadedFile
    events:
      - http:
          path: ladok/parse
          method: post
          cors: true

package:
  exclude:
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
    - node_modules/serverless-s3-local/**
    - /*.spec.js

resources:
  Resources:
    S3UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3UploadFolder}
    LadokParseResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.LadokParseResults}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    RecipientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.Recipients}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: companyCustomer
            AttributeType: S
          - AttributeName: ssn
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: companyCustomer
            KeySchema:
            - AttributeName: companyCustomer
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: ssn
            KeySchema:
            - AttributeName: ssn
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
