service: ladokParser

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  LadokParseResults: 'LadokParseResults-${self:provider.stage}'
  Recipients: 'Recipients-${self:provider.stage}'
  serverless-offline:
    port: 8080
    babelOptions:
      presets: ["env"]
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.LadokParseResults}
            sources: [./offline/seeds/ladokParseResults.json]
          - table: ${self:custom.Recipients}
            sources: [./offline/seeds/recipients.json]

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["LadokParseResultsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["RecipientsDynamoDBTable", "Arn" ] }
  environment:
    LadokParseResults: ${self:custom.LadokParseResults}
    Recipients: ${self:custom.Recipients}

functions:
  getNewAssignments:
    handler: src/lambda/getAssignments.getNewAssignments
    events:
      - http:
          path: assignments/get
          method: get
          cors: true

  saveNewAssignments:
    handler: src/lambda/saveAssignments.saveNewAssignments
    events:
      - http:
          path: assignments/save
          method: put
          cors: true

  parseUploadedFile:
    handler: src/lambda/parse.parseUploadedFile
    events:
      - http:
          path: ladok/parse
          method: post
          cors: true
package:
  exclude:
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**

resources:
  Resources:
    LadokParseResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.LadokParseResults}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    RecipientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.Recipients}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: companyCustomer
            AttributeType: S
          - AttributeName: ssn
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: companyCustomer
            KeySchema:
            - AttributeName: companyCustomer
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: ssn
            KeySchema:
            - AttributeName: ssn
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
